/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.airlinereservationsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Md Rizwan
 */
public class AddFlight extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddFlight
     */
    String driverClassName ="com.mysql.cj.jdbc.Driver";
    String URL = "jdbc:mysql://localhost:3306/airlinesystem";
    String root = "root";
    String password = "System123";
    public AddFlight() {
        initComponents();
        autoId();
    }
    Connection con;
    PreparedStatement pre;
    public void db_connection(){
        try {
            try {
                Class.forName(driverClassName);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AddFlight.class.getName()).log(Level.SEVERE, null, ex);
            }
            con=DriverManager.getConnection(URL,root,password);
        } catch (SQLException ex) {
            Logger.getLogger(AddFlight.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void autoId(){
        try {
            try {
                Class.forName(driverClassName);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AddFlight.class.getName()).log(Level.SEVERE, null, ex);
            }
            con = DriverManager.getConnection(URL,root,password);
            java.sql.Statement s = con.createStatement();
            String query = "Select MAX(FlightId) from Flights";
            ResultSet rs =  s.executeQuery(query);
            rs.next();
            String flightId = rs.getString("MAX(FlightId)");
            if(flightId ==  null){
                txt_flight_id.setText("FLT001");
            }else{
                long id = Long.parseLong(flightId.substring(3, flightId.length()));
                id++;
                txt_flight_id.setText("FLT"+String.format("%03d", id));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(AddFlight.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_flight_name = new javax.swing.JTextField();
        lbl_flightDetails = new javax.swing.JLabel();
        txt_departure = new javax.swing.JTextField();
        btn_add_flight = new javax.swing.JButton();
        lbl_dob2 = new javax.swing.JLabel();
        lbl_dob3 = new javax.swing.JLabel();
        lbl_dob6 = new javax.swing.JLabel();
        txt_flight_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lbl_dob7 = new javax.swing.JLabel();
        flight_date = new com.toedter.calendar.JDateChooser();
        lbl_dob8 = new javax.swing.JLabel();
        txt_arrival = new javax.swing.JTextField();
        txt_seat_left = new javax.swing.JTextField();
        lbl_dob9 = new javax.swing.JLabel();
        txt_fare = new javax.swing.JTextField();
        txt_time = new javax.swing.JTextField();
        lbl_dob10 = new javax.swing.JLabel();
        lbl_dob11 = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JButton();

        setClosable(true);
        setTitle("Add Flight Panel");
        setPreferredSize(new java.awt.Dimension(850, 500));
        setVisible(true);

        txt_flight_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_flight_nameActionPerformed(evt);
            }
        });

        lbl_flightDetails.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lbl_flightDetails.setForeground(new java.awt.Color(255, 0, 0));
        lbl_flightDetails.setText("Flight Details");

        txt_departure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_departureActionPerformed(evt);
            }
        });

        btn_add_flight.setText("Add Flight");
        btn_add_flight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_flightActionPerformed(evt);
            }
        });

        lbl_dob2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbl_dob2.setText("Flight Name");

        lbl_dob3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbl_dob3.setText("Departure");

        lbl_dob6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbl_dob6.setText("Flight Id ");

        txt_flight_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_flight_idActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Add New Flight");

        lbl_dob7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbl_dob7.setText("Date");

        lbl_dob8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbl_dob8.setText("Arival");

        txt_arrival.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_arrivalActionPerformed(evt);
            }
        });

        txt_seat_left.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_seat_leftActionPerformed(evt);
            }
        });

        lbl_dob9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbl_dob9.setText("Fare");

        txt_fare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fareActionPerformed(evt);
            }
        });

        txt_time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timeActionPerformed(evt);
            }
        });

        lbl_dob10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbl_dob10.setText("Seat Left");

        lbl_dob11.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbl_dob11.setText("Travel Time");

        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(292, 292, 292))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_dob2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_flight_name))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_dob8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_arrival))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_dob7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(flight_date, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_dob3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_departure, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_dob11, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_time))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_dob10, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_seat_left, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_dob9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_fare, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(lbl_flightDetails))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lbl_dob6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(txt_flight_id, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(btn_add_flight)
                        .addGap(35, 35, 35)
                        .addComponent(btn_cancel)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_dob6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_flight_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_flightDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_dob2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_flight_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_arrival, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_dob8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_departure, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_dob3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_dob10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_seat_left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_fare, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_dob9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_time, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_dob11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_dob7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(flight_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add_flight)
                    .addComponent(btn_cancel))
                .addGap(260, 260, 260))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_flight_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_flight_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_flight_nameActionPerformed

    private void txt_departureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_departureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_departureActionPerformed

    private void btn_add_flightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_flightActionPerformed
        try {
            // TODO add your handling code here:
            db_connection();
            String FlightId = txt_flight_id.getText();
            String FlightName = txt_flight_name.getText();
            String Arrival = txt_arrival.getText();
            String Departure = txt_departure.getText();
            DateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
            String Date = dt.format(flight_date.getDate());
            String SeatsLeft = txt_seat_left.getText();
            String Fare = txt_fare.getText();
            String TravelTime = txt_time.getText();
            con=DriverManager.getConnection(URL,root,password);
            String insert  ="Insert into flights(Flightid,FlightName,Arrival,Departure,Date,SeatLeft,Fare,TravelTime)values(?,?,?,?,?,?,?,?)";
            pre = con.prepareStatement(insert);
            pre.setString(1, FlightId);
            pre.setString(2, FlightName);
            pre.setString(3, Arrival);
            pre.setString(4, Departure);
            pre.setString(5, Date);
            pre.setString(6, SeatsLeft);
            pre.setString(7, Fare);
            pre.setString(8, TravelTime);
            pre.executeUpdate();
            JOptionPane.showMessageDialog(null, "Flight Addedd Successfully!");
            resetFields();
            autoId();
            
            
            
            
            
            
            
            
            
            
            
                    } catch (SQLException ex) {
            Logger.getLogger(AddFlight.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_add_flightActionPerformed

    private void txt_flight_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_flight_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_flight_idActionPerformed

    private void txt_arrivalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_arrivalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_arrivalActionPerformed

    private void txt_seat_leftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_seat_leftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_seat_leftActionPerformed

    private void txt_fareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fareActionPerformed

    private void txt_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timeActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btn_cancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_flight;
    private javax.swing.JButton btn_cancel;
    private com.toedter.calendar.JDateChooser flight_date;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_dob10;
    private javax.swing.JLabel lbl_dob11;
    private javax.swing.JLabel lbl_dob2;
    private javax.swing.JLabel lbl_dob3;
    private javax.swing.JLabel lbl_dob6;
    private javax.swing.JLabel lbl_dob7;
    private javax.swing.JLabel lbl_dob8;
    private javax.swing.JLabel lbl_dob9;
    private javax.swing.JLabel lbl_flightDetails;
    private javax.swing.JTextField txt_arrival;
    private javax.swing.JTextField txt_departure;
    private javax.swing.JTextField txt_fare;
    private javax.swing.JTextField txt_flight_id;
    private javax.swing.JTextField txt_flight_name;
    private javax.swing.JTextField txt_seat_left;
    private javax.swing.JTextField txt_time;
    // End of variables declaration//GEN-END:variables

    public void resetFields() {
        txt_time.setText("");
        txt_seat_left.setText("");
        txt_flight_name.setText("");
        txt_fare.setText("");
        txt_departure.setText("");
        txt_arrival.setText("");
        flight_date.setDate(null);
        
    }
}
