/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.airlinereservationsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Md Rizwan
 */
public class BookTicket extends javax.swing.JInternalFrame {

    /**
     * Creates new form BookTicket
     */
     
    String driverClassName ="com.mysql.cj.jdbc.Driver";
    String URL = "jdbc:mysql://localhost:3306/airlinesystem";
    String root = "root";
    String password = "System123";
    public BookTicket() {
        initComponents();
        autoId();
    }
    Connection con;
    PreparedStatement pre;
     public void db_connection(){
        try {
            try {
                Class.forName(driverClassName);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AddFlight.class.getName()).log(Level.SEVERE, null, ex);
            }
            con=DriverManager.getConnection(URL,root,password);
        } catch (SQLException ex) {
            Logger.getLogger(AddFlight.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
     public void autoId(){
        try {
            db_connection();
            java.sql.Statement s  =con.createStatement();
            String getId = "Select MAX(Ticket_Id) from tickets";
            ResultSet rs = s.executeQuery(getId);
            rs.next();
            String Id = rs.getString("MAX(Ticket_Id)");
            if(Id ==  null){
                txt_ticket_id.setText("TCK001");
            }else{
                long id = Long.parseLong(Id.substring(3,Id.length()));
                id++;
                txt_ticket_id.setText("TCK"+String.format("%03d", id));
            }
        
        
        } catch (SQLException ex) {
            Logger.getLogger(BookTicket.class.getName()).log(Level.SEVERE, null, ex);
        }
         
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_custid = new javax.swing.JLabel();
        txt_customer_id = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbl_dob2 = new javax.swing.JLabel();
        lbl_dob3 = new javax.swing.JLabel();
        btn_search_flight = new javax.swing.JButton();
        cmb_arrival = new javax.swing.JComboBox<>();
        cmb_departure = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        flightTable = new javax.swing.JTable();
        lbl_fname = new javax.swing.JLabel();
        labl_lname = new javax.swing.JLabel();
        txt_lname = new javax.swing.JTextField();
        txt_fname = new javax.swing.JTextField();
        txt_phoneno = new javax.swing.JTextField();
        lbl_phoneno = new javax.swing.JLabel();
        txt_fare = new javax.swing.JTextField();
        lbl_phoneno1 = new javax.swing.JLabel();
        lbl_phoneno2 = new javax.swing.JLabel();
        no_of_ticekts = new javax.swing.JSpinner();
        btn_cancel = new javax.swing.JButton();
        btn_bookticket = new javax.swing.JButton();
        lbl_phoneno3 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        txt_ticket_id = new javax.swing.JTextField();
        lbl_custid1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_cancel1 = new javax.swing.JButton();
        lbl_phoneno4 = new javax.swing.JLabel();
        lbl_seatleft = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Booking Panel");
        setPreferredSize(new java.awt.Dimension(850, 500));

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Customer Details");

        lbl_custid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_custid.setText("Customer ID ");

        txt_customer_id.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_customer_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_customer_idActionPerformed(evt);
            }
        });

        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("Flight Booking Panel");

        lbl_dob2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbl_dob2.setText("Arrival");

        lbl_dob3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbl_dob3.setText("Departure");

        btn_search_flight.setText("Search Flight");
        btn_search_flight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search_flightActionPerformed(evt);
            }
        });

        cmb_arrival.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select---", "Delhi", "Goa", "Mumbai", "Bangaloe", "Hyderabad", "Chennai", "Bidar", "Bagdogra", "Gurgaon", "Nasik", "Shirnagar", "Kashmir" }));

        cmb_departure.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select---", "Delhi", "Goa", "Mumbai", "Bangaloe", "Hyderabad", "Chennai", "Bidar", "Bagdogra", "Gurgaon", "Nasik", "Shirnagar", "Kashmir" }));

        flightTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Flight ID", "Flight Name", "Arrival", "Departure", "Date"
            }
        ));
        flightTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flightTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(flightTable);

        lbl_fname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_fname.setText("First Name");

        labl_lname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labl_lname.setText("Last Name");

        txt_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fnameActionPerformed(evt);
            }
        });

        lbl_phoneno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_phoneno.setText("Phone No");

        lbl_phoneno1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_phoneno1.setText("Fare");

        lbl_phoneno2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_phoneno2.setText("No of Ticekts");

        no_of_ticekts.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                no_of_ticektsStateChanged(evt);
            }
        });

        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_bookticket.setText("Book Ticekt");
        btn_bookticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bookticketActionPerformed(evt);
            }
        });

        lbl_phoneno3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_phoneno3.setText("Total Fare");

        txt_ticket_id.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_ticket_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ticket_idActionPerformed(evt);
            }
        });

        lbl_custid1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_custid1.setText("Ticekt ID");

        jLabel3.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 255));
        jLabel3.setText("Search Flight");

        btn_cancel1.setText("Reset");
        btn_cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancel1ActionPerformed(evt);
            }
        });

        lbl_phoneno4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_phoneno4.setText("Seat Left");

        lbl_seatleft.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_seatleft.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(121, 121, 121))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_arrival, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(lbl_dob2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(lbl_dob3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cmb_departure, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_search_flight))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_phoneno3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_custid)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_customer_id, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_phoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lbl_fname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labl_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbl_phoneno1))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_phoneno)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txt_fare, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbl_phoneno2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(no_of_ticekts, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txt_lname, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txt_fname, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl_phoneno4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_seatleft, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 95, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(lbl_custid1)
                        .addGap(26, 26, 26)
                        .addComponent(txt_ticket_id, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_bookticket)
                .addGap(18, 18, 18)
                .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_cancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(322, 322, 322))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ticket_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_custid1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labl_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_custid, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_customer_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_search)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_phoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_phoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_phoneno1)
                            .addComponent(txt_fare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_phoneno2)
                            .addComponent(no_of_ticekts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_phoneno3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_phoneno4)
                                .addComponent(lbl_seatleft))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_dob3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_dob2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_arrival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_departure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_search_flight))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_bookticket)
                    .addComponent(btn_cancel)
                    .addComponent(btn_cancel1))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_customer_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_customer_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_customer_idActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        try {
            // TODO add your handling code here:
            db_connection();
            String CustomerId = txt_customer_id.getText();
            String query = "Select * from customer where CustomerId=?";
            pre = con.prepareStatement(query);
            pre.setString(1, CustomerId);
            ResultSet rs = pre.executeQuery();
            if(rs.next()){
                txt_fname.setText(rs.getString("FirstName"));
                txt_lname.setText(rs.getString("LastName"));
                txt_phoneno.setText(rs.getString("PhoneNo"));
            }else{
                JOptionPane.showMessageDialog(null, "No Customer Available for this "+ CustomerId);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(BookTicket.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_search_flightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search_flightActionPerformed
         try {
             // TODO add your handling code here:
             String Arrival = cmb_arrival.getSelectedItem().toString();
             String Departure  =cmb_departure.getSelectedItem().toString();
             db_connection();
             String query ="Select * from flights where Arrival=? and Departure=?";
             pre = con.prepareStatement(query);
             pre.setString(1, Arrival);
             pre.setString(2, Departure);
             ResultSet rs = pre.executeQuery();
             ResultSetMetaData records = rs.getMetaData();
             int count = records.getColumnCount();
            
            DefaultTableModel dft = (DefaultTableModel)flightTable.getModel();
            dft.setRowCount(0);
            while(rs.next()){
               Vector v = new Vector();
               for(int i=1; i<count; i++){
                   v.add(rs.getString("FlightId"));
                   v.add(rs.getString("FlightName"));
                   v.add(rs.getString("Arrival"));
                   v.add(rs.getString("Departure"));
                   v.add(rs.getString("Arrival"));

               }
               dft.addRow(v);
            }
            
             
         
         
         
         
         } catch (SQLException ex) {
             Logger.getLogger(BookTicket.class.getName()).log(Level.SEVERE, null, ex);
         }
        
    }//GEN-LAST:event_btn_search_flightActionPerformed

    private void txt_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fnameActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_bookticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bookticketActionPerformed
        try {
            // TODO add your handling code here:
            db_connection();
            String TicketId = txt_ticket_id.getText();
            String CustomerId = txt_customer_id.getText();
            String FirstName  =txt_fname.getText();
            String LastName = txt_lname.getText();
            String PhoneNo = txt_phoneno.getText();
            int col = 0;
            int row = flightTable.getSelectedRow();
            String FlightId = flightTable.getModel().getValueAt(row, col).toString();
            String fetch_flightDetails = "Select * from flights where FlightId=?";
            pre = con.prepareStatement(fetch_flightDetails);
            pre.setString(1, FlightId);
            ResultSet rs = pre.executeQuery();
            rs.next();
            String FlightName = rs.getString("FlightName");
            String Arrival  =rs.getString("Arrival");
            String Departure  = rs.getString("Departure");
            String Date = rs.getString("Date");               
            
            int Fare = Integer.parseInt(txt_fare.getText());
            int Seats = Integer.parseInt(no_of_ticekts.getValue().toString());
            int Total  =Integer.parseInt(txt_total.getText());
            String insert_ticket = "Insert into tickets(Ticket_Id,CustomerId,FirstName,LastName,PhoneNo,FlightId,FlightName,Arrival,Departure,Date,Fare,Seats,TotalFare)values(?,?,?,?,?,?,?,?,?,?,?,?,?)";
            pre = con.prepareStatement(insert_ticket);
            pre.setString(1, TicketId);
            pre.setString(2,CustomerId);
            pre.setString(3, FirstName);
            pre.setString(4,LastName);
            pre.setString(5, PhoneNo);
            pre.setString(6,FlightId);
            pre.setString(7, FlightName);
            pre.setString(8,Arrival);
            pre.setString(9, Departure);
            pre.setString(10,Date);
            pre.setInt(11, Fare);
            pre.setInt(12,Seats);
            pre.setInt(13, Total);
            pre.executeUpdate();
            
            // Updating Available Seats.
            int seatsLeft = Integer.parseInt(lbl_seatleft.getText());
            String updateSeats = "Update flights set SeatLeft=? where FlightId=?";
            pre = con.prepareStatement(updateSeats);
            pre.setInt(1, seatsLeft);
            pre.setString(2, FlightId);
            pre.executeUpdate();
            JOptionPane.showMessageDialog(null, "Hey!   "+FirstName +" " +LastName+"   "+Seats +" Ticket Booked Successfully!");
            resetFields();
            autoId();
            
            
        } catch (SQLException ex) {
            Logger.getLogger(BookTicket.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_btn_bookticketActionPerformed

    private void flightTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flightTableMouseClicked
        try {
            // TODO add your handling code here:
            db_connection();
            java.sql.Statement s = con.createStatement();
            int col = 0;
            int row = flightTable.getSelectedRow();
            String id = flightTable.getModel().getValueAt(row, col).toString();
            String query = "Select * from flights where FlightId=?";
            pre = con.prepareStatement(query);
            pre.setString(1, id);
            ResultSet rs = pre.executeQuery();
            rs.next();
            txt_fare.setText(rs.getString("Fare"));    
            int seatsLeft = rs.getInt("SeatLeft");
            lbl_seatleft.setText(String.valueOf(seatsLeft));
        
        
        } catch (SQLException ex) {
            Logger.getLogger(BookTicket.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_flightTableMouseClicked

    private void no_of_ticektsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_no_of_ticektsStateChanged
        try {
            // TODO add your handling code here:
            int seats = Integer.parseInt(no_of_ticekts.getValue().toString());
            int fare =  Integer.parseInt(txt_fare.getText());
            int total = fare*seats;
            String value = String.valueOf(total);
            txt_total.setText(value);
            
            // Getiing flight Id
            int col = 0;
            int row = flightTable.getSelectedRow();
            String FlightId  = flightTable.getModel().getValueAt(row, col).toString();
            String getSeats = "Select * from flights where FlightId=?";
            pre = con.prepareStatement(getSeats);
            pre.setString(1, FlightId);
            ResultSet rs = pre.executeQuery();
            rs.next();
            int seatsLeft = rs.getInt("SeatLeft");
            int balanceSeats = 0;
            if(seats < seatsLeft || seats > 0){
                balanceSeats = seatsLeft-seats;
            }
            if(seats > seatsLeft){       
                JOptionPane.showMessageDialog(null, "You cannot book more than Available Seats of " + seatsLeft);
                no_of_ticekts.setValue(seatsLeft);
            }else if(seats <= -1){
                JOptionPane.showMessageDialog(null, "You cannot go below 0 seats");
                no_of_ticekts.setValue(0);
            }else{
                lbl_seatleft.setText(String.valueOf(balanceSeats));
            }
           
            
        
        
        } catch (SQLException ex) {
            Logger.getLogger(BookTicket.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_no_of_ticektsStateChanged

    private void txt_ticket_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ticket_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ticket_idActionPerformed

    private void btn_cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancel1ActionPerformed
        // TODO add your handling code here:
        resetFields();
    }//GEN-LAST:event_btn_cancel1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bookticket;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_cancel1;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_search_flight;
    private javax.swing.JComboBox<String> cmb_arrival;
    private javax.swing.JComboBox<String> cmb_departure;
    private javax.swing.JTable flightTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labl_lname;
    private javax.swing.JLabel lbl_custid;
    private javax.swing.JLabel lbl_custid1;
    private javax.swing.JLabel lbl_dob2;
    private javax.swing.JLabel lbl_dob3;
    private javax.swing.JLabel lbl_fname;
    private javax.swing.JLabel lbl_phoneno;
    private javax.swing.JLabel lbl_phoneno1;
    private javax.swing.JLabel lbl_phoneno2;
    private javax.swing.JLabel lbl_phoneno3;
    private javax.swing.JLabel lbl_phoneno4;
    private javax.swing.JLabel lbl_seatleft;
    private javax.swing.JSpinner no_of_ticekts;
    private javax.swing.JTextField txt_customer_id;
    private javax.swing.JTextField txt_fare;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_lname;
    private javax.swing.JTextField txt_phoneno;
    private javax.swing.JTextField txt_ticket_id;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables

    public void resetFields() {
        txt_total.setText("");
        txt_phoneno.setText("");
        txt_lname.setText("");
        txt_fname.setText("");
        txt_fare.setText("");
        txt_customer_id.setText("");
        DefaultTableModel table = (DefaultTableModel) flightTable.getModel();
        table.setRowCount(0);
        cmb_arrival.setSelectedItem("---Select---");
        cmb_departure.setSelectedItem("---Select---");   
        lbl_seatleft.setText("0");
       
    }
    
}
